### ISSUE TITLE
Enable sourcelink and deterministic builds

### ISSUE THREAD

**Issue by 304NotModified** [Drizin/InterpolatedLogging#2]
I would recommend this. See small examples here:

- https://github.com/NLog/NLog.Extensions.Logging/pull/439
- https://github.com/NLog/NLog.Extensions.Logging/pull/479

**Comment by Drizin** [comment]
@304NotModified thanks for the suggestion.
I've never used Sourcelink before, so I'd appreciate it if you can please review the associated commit? 
As far as I checked it's working - because in the generated nuspec I can see `<repository type="git" url="etc" commit="etc" />.` but just want to double check.

**Comment by 304NotModified** [comment]
I dont see anything strange,  but I recommended to check the nuget package with nuget package explorer: 
https://github.com/NuGetPackageExplorer/NuGetPackageExplorer

See https://github.com/NLog/NLog.Extensions.Logging/pull/479#issuecomment-808529410

**Comment by Drizin** [comment]
Thanks for the tool suggestion. Turns out that both Source Link and Deterministic Builds were not working :-( 

I could fix Source Link by adding the PDBs into the nupkg (yeah, I know that the current recommendation is to leave pdbs in a `snupkg` and upload it into a symbol server, but making it all together seems to be easier).

Took me lots of attempts to make the deterministic build work. Looks like using `dotnet pack` will randomly work (fails most of the time), while with `MSBuild` it works most of the time (or always). So basically I started using MSBuild to pack (like you do in NLog), which works better.

Thanks again for the advice and for the links!

**Comment by 304NotModified** [comment]
> Took me lots of attempts to make the deterministic build work. Looks like using dotnet pack will randomly work (fails most of the time),

That's because the parameter belongs to the build phase and not the pack, I guess

**Comment by 304NotModified** [comment]
> I could fix Source Link by adding the PDBs into the nupkg (yeah, I know that the current recommendation is to leave pdbs in a `snupkg` and upload it into a symbol server, but making it all together seems to be easier).

Creating a snupkg is pretty easy:

1. `/p:SymbolPackageFormat=snupkg` (msbuild)
2. Upload also the snupkg to nuget.org

**Comment by Drizin** [comment]
> That's because the parameter belongs to the build phase and not the pack, I guess

As far as I understood the `dotnet pack` also rebuilds (unless we specify `--no-build` which would get the existing build), and therefore the flag should work in both dotnet build and dotnet pack. 
So my wild guess is that dotnet tool is not correctly passing the flags or something (I've seen some other threads reporting issues with dotnet but none having issues with msbuild).

**Comment by 304NotModified** [comment]
looks great!

![image](https://user-images.githubusercontent.com/5808377/155211977-d76ea1f4-9640-4b82-a604-1cf93738c128.png)


(checked also the other 2)
